spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: huiqi
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  typeAliasesPackage: com.example.springbootdemo2.entity
  mapper-locations: classpath:mapper/UserMapper.xml

mvc:
    view:
      suffix: .ftl
      prefix: classpath:/templates/